<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWpf>true</UseWpf>
    <RootNamespace>exui_wpf</RootNamespace>
    <AssemblyName>exui_wpf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="templates\**\*" Exclude="templates\**\*.cs;templates\**\*.xaml" />
  </ItemGroup>
</Project>